name: Notify Telegram on PR Merge

on:
  pull_request:
    types:
      - closed  # This triggers the workflow when a PR is closed

jobs:
  notify-telegram:
    if: github.event.pull_request.merged == true  # Runs only if PR was merged
    runs-on: ubuntu-latest

    steps:
      - name: Send message to Telegram
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d text="🚀 PR #${{ github.event.pull_request.number }} has been merged to *${{ github.repository }}* by ${{ github.actor }}! 🎉"
